-- The fact at the staging grain, one row per source line. ETB_DCS_MCO stays out: the
-- dictionary has no entry for it, so no draft for it could be graded (ADR 0012).
-- Every column is cast to its contract type, as in every mart: dbt compares the type
-- names each adapter reports, so a type that changes upstream (an expression, a
-- Snowflake VARCHAR length) would fail the contract on one warehouse and not the other.
select
    cast(PRESTATION_KEY as varchar) as PRESTATION_KEY,
    cast(FLX_ANN_MOI as integer) as FLX_ANN_MOI,
    cast(ORG_CLE_REG as integer) as ORG_CLE_REG,
    cast(AGE_BEN_SNDS as integer) as AGE_BEN_SNDS,
    cast(BEN_RES_REG as integer) as BEN_RES_REG,
    cast(BEN_CMU_TOP as integer) as BEN_CMU_TOP,
    cast(BEN_QLT_COD as integer) as BEN_QLT_COD,
    cast(BEN_SEX_COD as integer) as BEN_SEX_COD,
    cast(DDP_SPE_COD as integer) as DDP_SPE_COD,
    cast(ETE_CAT_SNDS as integer) as ETE_CAT_SNDS,
    cast(ETE_REG_COD as integer) as ETE_REG_COD,
    cast(ETE_TYP_SNDS as integer) as ETE_TYP_SNDS,
    cast(ETP_REG_COD as integer) as ETP_REG_COD,
    cast(ETP_CAT_SNDS as integer) as ETP_CAT_SNDS,
    cast(MDT_TYP_COD as integer) as MDT_TYP_COD,
    cast(MFT_COD as integer) as MFT_COD,
    cast(PRS_FJH_TYP as integer) as PRS_FJH_TYP,
    cast(PRS_ACT_COG as decimal(18, 2)) as PRS_ACT_COG,
    cast(PRS_ACT_NBR as integer) as PRS_ACT_NBR,
    cast(PRS_ACT_QTE as integer) as PRS_ACT_QTE,
    cast(PRS_DEP_MNT as decimal(18, 2)) as PRS_DEP_MNT,
    cast(PRS_PAI_MNT as decimal(18, 2)) as PRS_PAI_MNT,
    cast(PRS_REM_BSE as decimal(18, 2)) as PRS_REM_BSE,
    cast(PRS_REM_MNT as decimal(18, 2)) as PRS_REM_MNT,
    cast(FLT_ACT_COG as decimal(18, 2)) as FLT_ACT_COG,
    cast(FLT_ACT_NBR as integer) as FLT_ACT_NBR,
    cast(FLT_ACT_QTE as integer) as FLT_ACT_QTE,
    cast(FLT_PAI_MNT as decimal(18, 2)) as FLT_PAI_MNT,
    cast(FLT_DEP_MNT as decimal(18, 2)) as FLT_DEP_MNT,
    cast(FLT_REM_MNT as decimal(18, 2)) as FLT_REM_MNT,
    cast(SOI_ANN as varchar) as SOI_ANN,
    cast(SOI_MOI as varchar) as SOI_MOI,
    cast(ASU_NAT as integer) as ASU_NAT,
    cast(ATT_NAT as integer) as ATT_NAT,
    cast(CPL_COD as integer) as CPL_COD,
    cast(CPT_ENV_TYP as integer) as CPT_ENV_TYP,
    cast(DRG_AFF_NAT as integer) as DRG_AFF_NAT,
    cast(ETE_IND_TAA as integer) as ETE_IND_TAA,
    cast(EXO_MTF as integer) as EXO_MTF,
    cast(MTM_NAT as integer) as MTM_NAT,
    cast(PRS_NAT as integer) as PRS_NAT,
    cast(PRS_PPU_SEC as integer) as PRS_PPU_SEC,
    cast(PRS_REM_TAU as decimal(18, 2)) as PRS_REM_TAU,
    cast(PRS_REM_TYP as integer) as PRS_REM_TYP,
    cast(PRS_PDS_QCP as integer) as PRS_PDS_QCP,
    cast(EXE_INS_REG as integer) as EXE_INS_REG,
    cast(PSE_ACT_SNDS as integer) as PSE_ACT_SNDS,
    cast(PSE_ACT_CAT as integer) as PSE_ACT_CAT,
    cast(PSE_SPE_SNDS as integer) as PSE_SPE_SNDS,
    cast(PSE_STJ_SNDS as integer) as PSE_STJ_SNDS,
    cast(PRE_INS_REG as integer) as PRE_INS_REG,
    cast(PSP_ACT_SNDS as integer) as PSP_ACT_SNDS,
    cast(PSP_ACT_CAT as integer) as PSP_ACT_CAT,
    cast(PSP_SPE_SNDS as integer) as PSP_SPE_SNDS,
    cast(PSP_STJ_SNDS as integer) as PSP_STJ_SNDS,
    cast(TOP_PS5_TRG as integer) as TOP_PS5_TRG
from {{ ref('stg_damir__prestations') }}
