"""The seeds hold the dictionary's code→label pairs, regenerated byte for byte, and nothing else."""

from __future__ import annotations

import re

import pytest
from code_list_seeds import SEED_DIR, SHEET, VARIABLES, code_lists, seeds, sheet_rows


def test_the_seeds_regenerate_byte_identically_from_the_dictionary() -> None:
    committed = {path.name: path.read_bytes() for path in sorted(SEED_DIR.glob("*.csv"))}
    assert seeds() == committed


def test_no_seed_holds_the_line_that_opens_its_list() -> None:
    # That line holds the dictionary's definition of the label, which drafts are
    # graded against; the warehouse must not carry it.
    openers = {str(row[0]): row[1] for row in sheet_rows(SHEET) if row and row[0] in VARIABLES}
    assert sorted(openers) == sorted(VARIABLES)
    for name, opener in openers.items():
        assert isinstance(opener, str)
        assert opener.strip() not in (SEED_DIR / f"{name.lower()}.csv").read_text()


def test_a_list_ends_at_its_first_blank_line() -> None:
    rows = [
        ("PSE_ACT_SNDS", "Libellé"),
        (50, "PHARMACIE"),
        (None, None),
        ("ASU_NAT", "Libellé"),
        (10, "MALADIE"),
    ]
    assert code_lists(rows, ["PSE_ACT_SNDS"]) == {"PSE_ACT_SNDS": [(50, "PHARMACIE")]}


@pytest.mark.parametrize(
    ("rows", "error"),
    [
        ([("X", "L"), ("01", "A")], "row 2 (X): code '01' is not an integer"),
        ([("X", "L"), (True, "A")], "row 2 (X): code True is not an integer"),
        ([("X", "L"), (1, " ")], "row 2 (X): no label for code 1"),
        ([("X", "L"), (1,)], "row 2 (X): no label for code 1"),
        ([("X", "L"), (1, "A"), (1, "B")], "row 3 (X): code 1 listed twice"),
        ([("X", "L"), (1, "A"), (None, "B"), (2, "C")], "row 3 (X): label 'B' has no code"),
        ([("X", "L"), (), ("X", "L")], "row 3: a second code list for X"),
        ([("Y", "L"), (1, "A")], "no code list for X"),
    ],
)
def test_a_malformed_list_fails_with_its_row(rows: list[tuple[object, ...]], error: str) -> None:
    with pytest.raises(ValueError, match=re.escape(error)):
        code_lists(rows, ["X"])
